# Generated by Django 2.1.7 on 2019-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
