# Generated by Django 2.1.7 on 2019-03-30 23:15

from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_data_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'new'), ('ok', 'ok'), ('unreachable', 'unreachable'), ('error', 'error')], max_length=11, verbose_name='State')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', jsonfallback.fields.FallbackJSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_response',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='log',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='events.Event'),
        ),
    ]
